#%RAML 1.0 NamedExample
value:
  order_id: abc123
  store_id: 3341
  store_name: Dallas Neighborhood Market
  store_address: 6185 Retail Rd, Dallas, TX, US (75231)   
  store_distance: 5.68
  store_contact_number: 5436781
  product_type_id: 709  
  quantity: 100